if(!self.__appxInited) {
self.__appxInited = 1;


require('./config$');


var AFAppX = self.AFAppX;
self.getCurrentPages = AFAppX.getCurrentPages;
self.getApp = AFAppX.getApp;
self.Page = AFAppX.Page;
self.App = AFAppX.App;
self.my = AFAppX.bridge || AFAppX.abridge;
self.abridge = self.my;
self.Component = AFAppX.WorkerComponent || function(){};
self.$global = AFAppX.$global;


function success() {
require('../../app');
require('../../component/demand-publish-view/demand-publish-view');
require('../../pages/index/index');
require('../../pages/catHouse/catHouse');
require('../../pages/fosterage/display/display');
require('../../pages/comment/trainer/found/found');
require('../../pages/comment/found/found');
require('../../pages/me/me');
require('../../pages/insurance/flow/flow');
require('../../pages/insurance/found/found');
require('../../pages/news/demo/demo');
require('../../pages/my/job/job');
require('../../pages/distinguish/found/found');
require('../../pages/distinguish/display/display');
require('../../pages/user/display/display');
require('../../pages/my/userInfo/userInfo');
require('../../pages/insurance/hospitalList/hospitalList');
require('../../pages/insurance/display/display');
require('../../pages/demand/display/display');
require('../../pages/demand/list/list');
require('../../pages/family/display/display');
require('../../pages/demand/found/found');
require('../../pages/personal/display/display');
require('../../pages/insurance/introduce/introduce');
require('../../pages/insurance/petList/petList');
require('../../pages/my/pet/pet');
require('../../pages/pet/found/found');
require('../../pages/my/insurance/insurance');
require('../../pages/insurance/instructions/instructions');
require('../../pages/personal/list/list');
require('../../pages/family/base/base');
require('../../pages/my/serverData/serverData');
require('../../pages/trainer/display/display');
require('../../pages/my/fosterage/fosterage');
require('../../pages/my/follow/follow');
require('../../pages/fosterage/trainer/display/display');
require('../../pages/comment/trainer/list/list');
require('../../pages/comment/trainer/display/display');
require('../../pages/fosterage/trainer/found/found');
require('../../pages/trainer/addServer/addServer');
require('../../pages/personal/serverList/serverList');
require('../../pages/trainer/remark/remark');
require('../../pages/trainer/trainerDetail/trainerDetail');
require('../../pages/family/flow/flow');
require('../../pages/trainer/flow/flow');
require('../../pages/trainer/base/base');
require('../../pages/colligate/authentication/authentication');
require('../../pages/trainer/video/video');
require('../../pages/colligate/bindPhone/bindPhone');
require('../../pages/store/storeInfo/storeInfo');
require('../../pages/store/describe/describe');
require('../../pages/family/upload/upload');
require('../../pages/store/flow/flow');
require('../../pages/family/experience/experience');
require('../../pages/family/incomeRecord/incomeRecord');
require('../../pages/family/master/master');
require('../../pages/colligate/addAddress/addAddress');
require('../../pages/family/familyInfo/familyInfo');
require('../../pages/family/others/others');
require('../../pages/family/provide/provide');
require('../../pages/family/describe/describe');
require('../../pages/colligate/webview/webview');
require('../../pages/family/invite/share/share');
require('../../pages/family/invite/list/list');
require('../../pages/calendar/calendar');
require('../../pages/activity/october/october');
require('../../pages/fosterage/found/found');
require('../../pages/my/coupon/coupon');
require('../../pages/pet/selectVarieties/selectVarieties');
require('../../pages/pet/display/display');
require('../../pages/comment/list/list');
require('../../pages/comment/display/display');
require('../../pages/colligate/aboutUs/aboutUs');
require('../../pages/colligate/selectAddress/selectAddress');
require('../../pages/colligate/search/search');
require('../../pages/pet/list/list');
require('../../pages/knowledge/display/display');
require('../../pages/colligate/feedback/feedback');
require('../../pages/my/detailed/detailed');
require('../../pages/my/wallet/wallet');
require('../../pages/my/setUp/setUp');
require('../../pages/my/demand/demand');
require('../../pages/news/list/list');
require('../../pages/news/display/display');
require('../../pages/news/notice/notice');
require('../../pages/fosterage/advanceFinish/advanceFinish');
require('../../pages/colligate/guarantee/guarantee');
require('../../pages/pet/petModule/petModule');
require('../../pages/fosterage/cancelReason/cancelReason');
require('../../pages/activity/insurance/insurance');
require('../../pages/search/search');
require('../../pages/colligate/errPrompt/errPrompt');
}
self.bootstrapApp ? self.bootstrapApp({ success }) : success();
}